  services:
  - name: prometheusConfig
    fileName: '{{ .ConfFileLocation }}'
    contents: |
      # Copyright (c) YugaByte, Inc.

      global:
        # By default, scrape targets every 15 seconds.
        scrape_interval:     {{ yamlPath ".prometheus.scrapeInterval" }}s
        evaluation_interval: {{ yamlPath ".prometheus.evaluationInterval" }}s
        # scrape_timeout is set to the global default (10s).

        # The labels to add to any time series or alerts when communicating with
        # external systems (federation, remote storage, Alertmanager).
        external_labels:
          monitor: 'swamper'

      rule_files:
      - '{{ .DataDir }}/swamper_rules/yugaware.ad.*.yml'
      - '{{ .DataDir }}/swamper_rules/yugaware.recording-rules.yml'

      # A list of scrape configurations.
      scrape_configs:

      - job_name: 'prometheus'
        scrape_interval: 10s
        scrape_timeout:  {{ yamlPath ".prometheus.scrapeTimeout" }}s
        static_configs:
          - targets: ['127.0.0.1:{{ yamlPath ".prometheus.externalPort" }}']

      - job_name: 'platform'
        scheme: https
        tls_config:
            insecure_skip_verify: true
        scrape_timeout:  {{ yamlPath ".prometheus.scrapeTimeout" }}s
        metrics_path: "/api/v1/prometheus_metrics"
        static_configs:
          - targets: ['127.0.0.1:{{ yamlPath ".platform.containerExposedPort" }}']

      - job_name: "node"
        file_sd_configs:
          - files:
            - '{{ .DataDir }}/swamper_targets/node.*.json'
        metric_relabel_configs:
        # Below relabels are required for smooth migration from node_exporter 0.13.0 to latest
        - source_labels: ["__name__"]
          regex: "node_cpu"
          target_label: "__name__"
          replacement: "node_cpu_seconds_total"
        - source_labels: ["__name__"]
          regex: "node_filesystem_free"
          target_label: "__name__"
          replacement: "node_filesystem_free_bytes"
        - source_labels: ["__name__"]
          regex: "node_filesystem_size"
          target_label: "__name__"
          replacement: "node_filesystem_size_bytes"
        - source_labels: ["__name__"]
          regex: "node_disk_reads_completed"
          target_label: "__name__"
          replacement: "node_disk_reads_completed_total"
        - source_labels: ["__name__"]
          regex: "node_disk_writes_completed"
          target_label: "__name__"
          replacement: "node_disk_writes_completed_total"
        - source_labels: ["__name__"]
          regex: "node_memory_MemTotal"
          target_label: "__name__"
          replacement: "node_memory_MemTotal_bytes"
        - source_labels: ["__name__"]
          regex: "node_memory_Slab"
          target_label: "__name__"
          replacement: "node_memory_Slab_bytes"
        - source_labels: ["__name__"]
          regex: "node_memory_Cached"
          target_label: "__name__"
          replacement: "node_memory_Cached_bytes"
        - source_labels: ["__name__"]
          regex: "node_memory_Buffers"
          target_label: "__name__"
          replacement: "node_memory_Buffers_bytes"
        - source_labels: ["__name__"]
          regex: "node_memory_MemFree"
          target_label: "__name__"
          replacement: "node_memory_MemFree_bytes"
        - source_labels: ["__name__"]
          regex: "node_network_receive_bytes"
          target_label: "__name__"
          replacement: "node_network_receive_bytes_total"
        - source_labels: ["__name__"]
          regex: "node_network_transmit_bytes"
          target_label: "__name__"
          replacement: "node_network_transmit_bytes_total"
        - source_labels: ["__name__"]
          regex: "node_network_receive_packets"
          target_label: "__name__"
          replacement: "node_network_receive_packets_total"
        - source_labels: ["__name__"]
          regex: "node_network_transmit_packets"
          target_label: "__name__"
          replacement: "node_network_transmit_packets_total"
        - source_labels: ["__name__"]
          regex: "node_network_receive_errs"
          target_label: "__name__"
          replacement: "node_network_receive_errs_total"
        - source_labels: ["__name__"]
          regex: "node_network_transmit_errs"
          target_label: "__name__"
          replacement: "node_network_transmit_errs_total"
        - source_labels: ["__name__"]
          regex: "node_disk_bytes_read"
          target_label: "__name__"
          replacement: "node_disk_read_bytes_total"
        - source_labels: ["__name__"]
          regex: "node_disk_bytes_written"
          target_label: "__name__"
          replacement: "node_disk_written_bytes_total"
        # saved_name relabel goes last to get correct label names after above relabels
        - source_labels: ["__name__"]
          regex: "(.*)"
          target_label: "saved_name"
          replacement: "$1"

      - job_name: "yugabyte"
        metrics_path: "/prometheus-metrics"
        params:
          # Enable priority regex on all tables
          # URL encoding done by prometheus
          priority_regex:
            - "rocksdb_(number_db_(next|seek)\
            |block_cache_(add|single_touch_add|multi_touch_add)\
            |current_version_(sst_files_size|num_sst_files)\
            |db_([^_]+_micros_[^_]+|mutex_wait_micros)|block_cache_(hit|miss)\
            |bloom_filter_(checked|useful)|stall_micros|flush_write_bytes\
            |compact_[^_]+_bytes|compaction_times_micros_[^_]+\
            |numfiles_in_singlecompaction_[^_]+)\
            |async_replication_[^_]+_lag_micros|transaction_conflicts\
            |majority_sst_files_rejections|expired_transactions\
            |log_(sync_latency_[^_]+|group_commit_latency_[^_]+\
            |append_latency_[^_]+|bytes_logged|reader_bytes_read\
            |append_latency_count|sync_latency_count|cache_size|cache_num_ops)\
            |glog_[^_]+_messages|follower_lag_ms"
        file_sd_configs:
          - files:
            - '{{ .DataDir }}/swamper_targets/yugabyte.*.json'
        metric_relabel_configs:
        - source_labels: ["__name__"]
          regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)"
          target_label: "server_type"
          replacement: "$1"
        - source_labels: ["__name__"]
          regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)"
          target_label: "service_type"
          replacement: "$2"
        - source_labels: ["__name__"]
          regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)"
          target_label: "service_method"
          replacement: "$3"
        - source_labels: ["__name__"]
          regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)"
          target_label: "__name__"
          replacement: "rpc_latency$4"
        - source_labels: ["__name__"]
          regex: "(.*)"
          target_label: "saved_name"
          replacement: "$1"

  - name: prometheusService
    fileName: "{{ .SystemdFileLocation }}"
    contents: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=yugabyte
      Group=yugabyte
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
      --config.file {{ .ConfFileLocation }} \
      --storage.tsdb.path {{ .DataDir }}/storage \
      --web.console.templates={{ .PromDir }}/consoles \
      --web.console.libraries={{ .PromDir }}/console_libraries \
      --web.enable-admin-api \
      --web.enable-lifecycle \
      --web.listen-address=:{{ yamlPath ".prometheus.externalPort" }} \
      --query.max-concurrency={{ yamlPath ".prometheus.maxConcurrency" }} \
      --query.max-samples={{ yamlPath ".prometheus.maxSamples" }} \
      --query.timeout={{ yamlPath ".prometheus.timeout" }}s

      Restart=always
      RestartSec={{ yamlPath ".prometheus.restartSeconds"}}

      [Install]
      WantedBy=multi-user.target
