- name: Install OpenTelemetry collector | Set paths part 1
  set_fact:
    otel_col_temp_path: "{{ remote_tmp_dir | default('/tmp') }}/otel-collector"
    otel_col_package_file: "otelcol-contrib_{{ otel_col_version }}_{{ otel_col_platform }}_{{ otel_col_arch }}.tar.gz"
    _mount_points: "{{ mount_points.split(',') }}"

- name: Install OpenTelemetry collector | Set paths part 2
  set_fact:
    otel_col_local_path: "{{ local_package_path }}/{{ otel_col_package_file }}"
    _mount_logs_dir: "{{ _mount_points[0] }}/otel-collector/logs"
    _mount_psq_dir: "{{ _mount_points[0] }}/otel-collector/psq"

- name: Install OpenTelemetry collector | Clean up OpenTelemetry collector temp directory
  file:
    path: "{{ otel_col_temp_path }}"
    state: absent

- name: Install OpenTelemetry collector | Create OpenTelemetry collector temp directory
  file:
    path: "{{ otel_col_temp_path }}"
    state: directory
    mode: 0755

- name: Install OpenTelemetry collector | Download and uncompress OpenTelemetry collector
  unarchive:
    src: "{{ otel_col_local_path }}"
    dest: "{{ otel_col_temp_path }}"
    copy: yes

- name: Install OpenTelemetry collector | Create OpenTelemetry collector directory
  file:
    path: "{{ otel_col_dir }}"
    state: directory
    mode: 0755

- name: Install OpenTelemetry collector | Copy unpacked collector files
  copy:
    src: "{{ otel_col_temp_path }}/"
    dest: "{{ otel_col_dir }}"
    remote_src: True

- name: Install OpenTelemetry collector | Ensure otelcol-contrib permissions.
  shell: |
    chmod -R 755 {{ otel_col_dir }}/otelcol-contrib

- name: Install OpenTelemetry collector | Clean up OpenTelemetry collector temp directory
  file:
    path: "{{ otel_col_temp_path }}"
    state: absent

- name: Install OpenTelemetry collector | Create OpenTelemetry collector logs directory
  file:
    path: "{{ _mount_logs_dir }}"
    state: directory
    mode: 0755

- name: Install OpenTelemetry collector | Symlink OpenTelemetry collector logs directory
  file:
    src: "{{ _mount_logs_dir }}"
    dest: "{{ otel_col_logs_dir }}"
    mode: 0755
    state: link
    force: yes

- name: Install OpenTelemetry collector | Create OpenTelemetry collector persistent queues directory
  file:
    path: "{{ _mount_psq_dir }}"
    state: directory
    mode: 0755

- name: Install OpenTelemetry collector | Symlink OpenTelemetry collector persistent queues directory
  file:
    src: "{{ _mount_psq_dir }}"
    dest: "{{ otel_col_psq_dir }}"
    mode: 0755
    state: link
    force: yes
