# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- name: Manage OpenTelemetry Collector
  hosts: "{{ yb_prebuilt_ami_host | default(instance_search_pattern) }}"
  roles:
    - "manage_otel_collector"
  vars_files:
    - "{{ vars_file | default(placeholder_vars_file) }}"
