# Copyright 2023 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

yb_home_dir: "/home/{{ user_name }}"
otel_col_dir: "{{ yb_home_dir }}/otel-collector"
otel_col_config_file: "{{ yb_home_dir }}/otel-collector/config.yml"
otel_col_logs_dir: "{{ yb_home_dir }}/otel-collector/logs"
otel_col_queue_dir: "{{ yb_home_dir }}/otel-collector/queue"
otel_col_version: "0.84.0"
otel_col_platform: "linux"
otel_col_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64'}}"
