apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storageconfigs.operator.yugabyte.io
spec:
  group: operator.yugabyte.io
  scope: Namespaced
  names:
    plural: storageconfigs
    singular: storageconfig
    kind: StorageConfig
  versions:
    - name: v1alpha1
      subresources:
        status: {}
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                message:
                  type: string
                success:
                  type: boolean
                resourceUUID:
                  type: string
            spec:
              type: object
              properties:
                config_type:
                  type: string
                  enum:
                    - STORAGE_S3
                    - STORAGE_NFS
                    - STORAGE_GCS
                data:
                  type: object
                  properties:
                    AWS_ACCESS_KEY_ID:
                      type: string
                    AWS_SECRET_ACCESS_KEY:
                      type: string
                    BACKUP_LOCATION:
                      type: string
                    GCS_CREDENTIALS_JSON:
                      type: string
