apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: support-bundles.operator.yugabyte.io
spec:
  group: operator.yugabyte.io
  scope: Namespaced
  names:
    plural: support-bundles
    singular: support-bundle
    kind: SupportBundle
    shortNames:
    - sb
  versions:
    - name: v1alpha1
      subresources:
        status: {}
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                status:
                  type: string
                  enum:
                  - generating
                  - ready
                  - failed
                access:
                  type: string
                resourceUUID:
                  type: string
            spec:
              type: object
              properties:
                universeName:
                  type: string
                collectionTimerange:
                  type: object
                  properties:
                    startDate:
                      type: string
                      example: 2022-12-12T13:07:18Z,
                      format: date-time
                    endDate:
                      type: string
                      example: 2022-12-12T13:07:18Z,
                      format: date-time
                  required:
                  - startDate
                components:
                  type: array
                  items:
                    type: string
                    enum:
                    - UniverseLogs
                    - ApplicationLogs
                    - OutputFiles
                    - ErrorFiles
                    - CoreFiles
                    - GFlags
                    - Instance
                    - ConsensusMeta
                    - TabletMeta
                    - YbcLogs
                    - K8sInfo
